### PR TITLE
Are you able to see me ????

### PR DESCRIPTION
**Pull request by SOCRATE85**
What is the name of the branch ?

Description of the branch

### CODE REVIEW

**Review by novoaurore — CHANGES_REQUESTED** [review]
please add one more file

**Comment by SOCRATE85** [comment]
> please add one more file

What type of file do you wanted ??

**Comment by novoaurore** [comment]
create soso.txt

**Comment by SOCRATE85** [comment]
> create soso.txt

I did it

**Comment by SOCRATE85** [comment]
> > create soso.txt
> 
> I did it

I will do the other one probably next sprint

**Review by novoaurore — APPROVED** [review]

**Pull request merged**
